In [59]:
# !pip install altair

In [66]:
# !pip install vega

Collecting vega
  Downloading vega-4.0.0-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 12.3 MB/s eta 0:00:0000:0100:01
Collecting ipytablewidgets<0.4.0,>=0.3.0 (from vega)
  Downloading ipytablewidgets-0.3.1-py2.py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 kB 13.9 MB/s eta 0:00:00
Collecting jupyter<2.0.0,>=1.0.0 (from vega)
  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting pandas<2.0.0,>=1.5.0 (from vega)
  Downloading pandas-1.5.3-cp310-cp310-macosx_10_9_x86_64.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 13.1 MB/s eta 0:00:0000:0100:01
Collecting ipywidgets<9,>=7.5.0 (from ipytablewidgets<0.4.0,>=0.3.0->vega)
  Downloading ipywidgets-8.0.7-py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.3/138.3 kB 9.5 MB/s eta 0:00:00
Requirement already satisfied: traitlets>=4.3.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipytablewidgets<0.4.0,>=0.3.0->vega) (5.9.0)
Collecting traittypes>=0.0.6 (from ipytablewidgets<0.4.0,>=0.3.0->vega)
  Downloading traittypes-0.2.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: numpy<2.0.0,>=1.10.4 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipytablewidgets<0.4.0,>=0.3.0->vega) (1.24.3)
Collecting lz4 (from ipytablewidgets<0.4.0,>=0.3.0->vega)
  Downloading lz4-4.3.2-cp310-cp310-macosx_10_9_x86_64.whl (254 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.2/254.2 kB 11.3 MB/s eta 0:00:00
Requirement already satisfied: notebook in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (6.5.4)
Collecting qtconsole (from jupyter<2.0.0,>=1.0.0->vega)
  Downloading qtconsole-5.4.3-py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.9/121.9 kB 11.0 MB/s eta 0:00:00
Collecting jupyter-console (from jupyter<2.0.0,>=1.0.0->vega)
  Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Requirement already satisfied: nbconvert in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (7.4.0)
Requirement already satisfied: ipykernel in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (6.23.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from pandas<2.0.0,>=1.5.0->vega) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from pandas<2.0.0,>=1.5.0->vega) (2023.3)
Requirement already satisfied: ipython>=6.1.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (8.14.0)
Collecting widgetsnbextension~=4.0.7 (from ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega)
  Downloading widgetsnbextension-4.0.8-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 14.5 MB/s eta 0:00:00a 0:00:01
Collecting jupyterlab-widgets~=3.0.7 (from ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega)
  Downloading jupyterlab_widgets-3.0.8-py3-none-any.whl (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.0/215.0 kB 10.2 MB/s eta 0:00:00
Requirement already satisfied: appnope in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.1.3)
Requirement already satisfied: comm>=0.1.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.1.3)
Requirement already satisfied: debugpy>=1.6.5 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (8.2.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (5.3.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.1.6)
Requirement already satisfied: nest-asyncio in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (1.5.6)
Requirement already satisfied: packaging in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (23.1)
Requirement already satisfied: psutil in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (5.9.5)
Requirement already satisfied: pyzmq>=20 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (25.1.0)
Requirement already satisfied: tornado>=6.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (6.3.2)
Requirement already satisfied: six>=1.5 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.5.0->vega) (1.16.0)
Requirement already satisfied: prompt-toolkit>=3.0.30 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->vega) (3.0.38)
Requirement already satisfied: pygments in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->vega) (2.15.1)
Requirement already satisfied: beautifulsoup4 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (4.12.2)
Requirement already satisfied: bleach in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (6.0.0)
Requirement already satisfied: defusedxml in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (3.1.2)
Requirement already satisfied: jupyterlab-pygments in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.2.2)
Requirement already satisfied: markupsafe>=2.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (2.1.3)
Requirement already satisfied: mistune<3,>=2.0.3 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (2.0.5)
Requirement already satisfied: nbclient>=0.5.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.8.0)
Requirement already satisfied: nbformat>=5.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (5.9.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.5.0)
Requirement already satisfied: tinycss2 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.2.1)

Requirement already satisfied: argon2-cffi in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (21.3.0)
Requirement already satisfied: ipython-genutils in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (0.2.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (0.17.1)
Requirement already satisfied: prometheus-client in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (0.17.0)
Requirement already satisfied: nbclassic>=0.4.7 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (1.0.0)
Collecting qtpy>=2.0.1 (from qtconsole->jupyter<2.0.0,>=1.0.0->vega)
  Downloading QtPy-2.3.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.9/84.9 kB 6.7 MB/s eta 0:00:00
Requirement already satisfied: backcall in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (0.2.0)
Requirement already satisfied: decorator in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (0.18.2)
Requirement already satisfied: pickleshare in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (0.7.5)
Requirement already satisfied: stack-data in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (0.6.2)
Requirement already satisfied: pexpect>4.3 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (4.8.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (3.5.1)
Requirement already satisfied: jupyter-server>=1.8 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (2.6.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (0.2.3)
Requirement already satisfied: fastjsonschema in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (2.17.1)
Requirement already satisfied: jsonschema>=2.6 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (4.17.3)
Requirement already satisfied: wcwidth in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter<2.0.0,>=1.0.0->vega) (0.2.6)
Requirement already satisfied: ptyprocess in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from terminado>=0.8.3->notebook->jupyter<2.0.0,>=1.0.0->vega) (0.7.0)
Requirement already satisfied: argon2-cffi-bindings in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->vega) (21.2.0)
Requirement already satisfied: soupsieve>1.2 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from beautifulsoup4->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (2.4.1)
Requirement already satisfied: webencodings in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from bleach->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (0.8.3)
Requirement already satisfied: attrs>=17.4.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.19.3)
Requirement already satisfied: anyio>=3.1.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (3.7.0)
Requirement already satisfied: jupyter-events>=0.6.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (0.6.3)
Requirement already satisfied: jupyter-server-terminals in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (0.4.4)
Requirement already satisfied: overrides in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (7.3.1)
Requirement already satisfied: websocket-client in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (1.5.3)
Requirement already satisfied: cffi>=1.0.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->vega) (1.15.1)
Requirement already satisfied: executing>=1.2.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (2.2.1)
Requirement already satisfied: pure-eval in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9,>=7.5.0->ipytablewidgets<0.4.0,>=0.3.0->vega) (0.2.2)
Requirement already satisfied: idna>=2.8 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from anyio>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (3.4)
Requirement already satisfied: sniffio>=1.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from anyio>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (1.3.0)
Requirement already satisfied: exceptiongroup in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from anyio>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (1.1.1)
Requirement already satisfied: pycparser in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->vega) (2.21)
Requirement already satisfied: python-json-logger>=2.0.4 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (2.0.7)

Requirement already satisfied: pyyaml>=5.3 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (6.0)
Requirement already satisfied: rfc3339-validator in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jupyter-events>=0.6.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter<2.0.0,>=1.0.0->vega) (0.1.1)
Requirement already satisfied: fqdn in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.5.1)
Requirement already satisfied: isoduration in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (2.3)
Requirement already satisfied: uri-template in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.2.0)
Requirement already satisfied: webcolors>=1.11 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.13)
Requirement already satisfied: arrow>=0.15.0 in /Users/ligeaalexander/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from isoduration->jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.2.3)
Installing collected packages: widgetsnbextension, traittypes, qtpy, lz4, jupyterlab-widgets, pandas, qtconsole, jupyter-console, ipywidgets, ipytablewidgets, jupyter, vega
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.2
    Uninstalling pandas-2.0.2:
      Successfully uninstalled pandas-2.0.2
Successfully installed ipytablewidgets-0.3.1 ipywidgets-8.0.7 jupyter-1.0.0 jupyter-console-6.6.3 jupyterlab-widgets-3.0.8 lz4-4.3.2 pandas-1.5.3 qtconsole-5.4.3 qtpy-2.3.1 traittypes-0.2.1 vega-4.0.0 widgetsnbextension-4.0.8

In [1]:
import json
import pandas as pd
import altair as alt

In [2]:
import re

# Reading in JSON Search Results from localize.city 

I focused only on available listings in and around Prospect Park, Brooklyn NYC and only 1 bedroom/studio apartments

In [3]:
def json_to_dict(filepath):
    with open(filepath, 'r') as file:
        data = json.load(file)
    return data

In [4]:
filepaths = [
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page1.json',
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page2.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page3.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page4.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page5.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page6.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page7.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page8.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page9.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page10.json',
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page11.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page12.json', 
    '/Users/ligeaalexander/Desktop/Developer/Project-2/brooklyn_prospect_listing_result_page13.json']

In [5]:
dictionaries = [json_to_dict(filepath) for filepath in filepaths]

In [6]:
print(type(dictionaries))
print(type(dictionaries[0]))
print(dictionaries[0].keys())

<class 'list'>
<class 'dict'>
dict_keys(['data'])

In [7]:
# dictionaries[0]

In [8]:
# listing = []

for i, dict in enumerate(dictionaries):
#     print(f"Page {i+1}, {[id['id']for id in dict['data']['searchResult']['poi']]}")
    print(len([id['id']for id in dict['data']['searchResult']['poi']]))
    print([id['id']for id in dict['data']['searchResult']['poi']])
    print('------')

20
['l-l4njo7ppbf0p', 'm-g7pk2u6bgdl7', 'm-k641hj441qsf', 'm-7m7ugsdf31rv', 'm-5l5sbh0q5cdi', 'm-fuijvl2a4kvv', 'm-9tfhakmgmkv0', 'm-f2aogop6554i', 'm-kde19bjr8f4m', 'm-eb8nghduno94', 'm-gjpbcj3u72fp', 'm-9htcac339ik7', 'm-k9oc9i9ffs63', 'm-6kf4148kfddl', 'm-cb9vbgu5rn5', 'm-au50rkfr98th', 'm-fo1rc16js34t', 'm-5ttk310iec4s', 'm-9p5ku13kfll7', 'm-ka79svpaihfr']
------
20
['m-lblh5t3riqfu', 'm-skv7aqh4s5gl', 'm-nsn2m4kkq9uv', 'm-oj749aepcagp', 'm-1u9m2efnbcup', 'm-cku3fm8oskfo', 'm-2errkn8o62in', 'm-7vhvbui4fp5j', 'm-i151fuv22n18', 'm-sul0cl5kusbl', 'm-993pbkgsnc3s', 'm-51a9boljs562', 'm-as4rgiinomc0', 'm-pjck846pllqe', 'm-alvdc30ctcdj', 'm-69fm2r7uflre', 'm-fq59hc0hh87d', 'm-tq3lbh8gge9h', 'm-6uduhgo2kok0', 'm-jgmipn7ma570']
------
20
['m-ffmjf51gcevs', 'm-5kvepkc92irh', 'm-rc3ivod718i5', 'm-k9jt5mb37vfv', 'm-gudu0jdt7h1m', 'm-ho8t8dtu3k75', 'm-p9epj5pvl9s9', 'm-vtmqugvur0oh', 'm-r256s2t33she', 'm-3av8il4tckpa', 'm-8h006k5elqa5', 'm-kn62klng7iho', 'm-da52rtlgbm82', 'm-hmcr9o9mt0hg', 'm-logs01fe96gg', 'm-rqfceepfnus6', 'l-vloo76lhui9', 'l-e0uuepcve088', 'l-33135ieoeo43', 'l-22radm21mj5t']
------
20
['l-mpa0bot1horv', 'l-niqhhmp2ao4d', 'l-s0q7bhrd5bm0', 'l-e8a60nod7grs', 'l-ucasbmn0ub45', 'l-b8bb2cfelnp4', 'l-he4hrhl1avo', 'l-33135ieoeo43', 'l-pbgo4et6bk1m', 'l-4dimfbh44tt1', 'l-tgfdpd9ecrhe', 'l-nib9q9ijgoff', 'l-7ulf3iisd6jj', 'l-22radm21mj5t', 'l-o0rngdr2memc', 'l-m5skrj161t0f', 'l-69f27upectfc', 'l-114i1asehvc2', 'l-i0241551hjsi', 'l-2k2qp70arkpo']
------
20
['l-mpa0bot1horv', 'l-niqhhmp2ao4d', 'l-s0q7bhrd5bm0', 'l-e8a60nod7grs', 'l-ucasbmn0ub45', 'l-b8bb2cfelnp4', 'l-he4hrhl1avo', 'l-pbgo4et6bk1m', 'l-4dimfbh44tt1', 'l-tgfdpd9ecrhe', 'l-nib9q9ijgoff', 'l-7ulf3iisd6jj', 'l-4glljujjq02r', 'l-2j6vsj8ohsed', 'l-5h12jeqvbuoa', 'l-qj7plb01m2m0', 'l-in1p3ctq1l7n', 'l-eiahqf0jgupq', 'l-g4j7ikr6d4rd', 'm-mmkvuj8atb97']
------
20
['m-d93k2e7dnm8o', 'm-dcs5mmvka7d4', 'm-e9b6pkj44jc6', 'l-j7tp78f9d067', 'l-bmvc0kl7vjcv', 'l-pru5m07pes8v', 'l-tjv2dj6n654n', 'm-1tp44rhahjol', 'm-pojnp3vuvgon', 'm-atlajse2nlai', 'm-j3eccqa5vr8k', 'm-al6cipi17nmp', 'm-r26svsp2etao', 'm-j9ub0uspt3lj', 'm-us93lqi46jma', 'm-th3e5gmna9m1', 'l-3ubttvff9u4r', 'l-l7ppcng5sq8v', 'l-mh9qfjcn1r9e', 'm-h21bsjgo95b0']
------
20
['m-bfdnogc97rm2', 'l-566a13ifc12a', 'l-iskt4hbdggaj', 'l-inje6git2s3', 'l-av061bbfimlb', 'l-47nnhcpcrano', 'l-b4hoklgqau8l', 'l-qh300dtif0ah', 'l-8jmgtcelkqau', 'l-475vglb54oai', 'l-bcukcl31jkl0', 'l-rv33e2rues2r', 'l-7471p5da5s4g', 'm-dnfmn18m8ae7', 'l-nqq3vjtc4n9k', 'l-c0dm8dl8fnab', 'l-ivltrfkc5kmm', 'l-skpvkqbbue9j', 'l-jm1qrmj40hlg', 'l-1ivun56qi299']
------
20
['l-srbn5ucmgbc0', 'l-5mt2g1dct183', 'l-vkhdtnq6trpi', 'm-bnkfi8dmj45k', 'm-qddqkcgm4vu0', 'm-2jnojj5ivupc', 'm-ioml7upjj0nf', 'm-1a68bqniv8f5', 'm-52krgvmtanfq', 'm-3h2b7f9f864', 'm-mllprmn7u2q', 'm-175u8hpq13uk', 'm-i7753l1falmj', 'm-39adoidr9t7j', 'm-qako0aep671j', 'm-fhjftpbgko0c', 'm-lkaovhe3vi2k', 'm-6jj3p09j1oaa', 'm-e9oadqrasp4k', 'm-4g38orid0ttu']
------
20
['m-4g38orid0ttu', 'm-8ac4uoe1n8ec', 'l-af04hjn8ih6a', 'l-e23oh50jf3js', 'l-q69hi8o4fh1u', 'l-o3ke9d887v04', 'm-dlb79be872u9', 'l-5sr3mraftvdo', 'l-9417psnrdkqb', 'm-oc27u40tqu3k', 'm-6aoa0jitd5d7', 'l-ue6jib37qqnf', 'l-94a2gjl0u1g1', 'l-88virisvsmsi', 'm-ha3scum2sgo1', 'm-3nne3j20j5cb', 'm-aopat6l3s9ej', 'm-59oq08252jg8', 'l-jmve9n9ak98q', 'l-eocm9b7e0ci1']
------
20
['m-gt9li0q09upv', 'm-440k5u8m85op', 'm-i7lj3vg57hhp', 'l-g8kqq3bhsigp', 'l-lf4rbiapfuqo', 'l-mfg3np6mqcgh', 'm-6647ng7l2sgm', 'm-8rdcg1kqnjh8', 'm-k53u06j4180', 'm-herq8clovjk4', 'm-qedem2h2qs8t', 'm-j80igb3rniuk', 'm-4sbq6mdg0dml', 'm-fhhsdl6rdr3b', 'm-f918uuvp2nuc', 'm-c4it0pjromg', 'm-msf6rb8peb05', 'm-cidleafi7fv7', 'l-b65oi9p4kfn6', 'l-a8m7jtmn1l8g']
------
20
['m-ngt4ph8udkmq', 'm-jmtr0spu4jut', 'm-dvmglep3gq88', 'l-4m0q83824jh4', 'l-3ruktjkghna8', 'm-84sipv8lrh8v', 'm-qmam6gq4qni9', 'l-qp91auide8ca', 'l-8eu4lc6s5t8o', 'm-jag808dc459v', 'l-9f5kcehflfmu', 'l-pngptb07ovrd', 'm-vpduu8qvbhim', 'm-ts3f6uqiskp3', 'm-19loqn2udrop', 'm-7l0sn2vijjtq', 'l-a3m6i3kr44j6', 'l-p6sepvkpkl3e', 'm-n6hdierg196s', 'm-tgv98j1easj5']
------
20
['m-5dpr3rp5de9l', 'm-c37itnq8l7r3', 'm-cppnnes2qq7u', 'l-aaum7dk0s54s', 'm-mosqba1euac8', 'm-j1imhv5kuv4m', 'l-o4a7mm1t56a2', 'm-qu0h333unbdg', 'l-nrca98729k7u', 'l-614av50ij5cb', 'l-m1cdv0oquami', 'l-ico56tofpl8q', 'l-dtlgbj17f16j', 'm-qhhbu9fogn0e', 'm-s2cdf4ftst12', 'm-as7sdoe4223s', 'm-du28k1ukeoap', 'l-1cumekhger73', 'l-tdbjur5f7qck', 'l-cb6cmjqnsonf']
------
20
['l-lhg6ms9181qh', 'm-1idrg5n5km56', 'm-qm4i8p3aakoa', 'm-5j7i6taerbmm', 'l-fm746g5qjbog', 'm-v83838enkoi8', 'l-pj7cvotqbson', 'l-elpemnn4kfbg', 'l-cvvnmpnf1hmf', 'l-706qhfcstnd2', 'm-105edfbi2h3k', 'm-eisl0jc823kj', 'l-aeasnlvah2gl', 'm-re8s2nn1ebt', 'm-6ilr6o8obk3c', 'm-t8p0q78tlp5k', 'm-a3poj9qc2mh8', 'l-40dte2cunttt', 'l-sk18vv1pjmct', 'm-9en3gqdfipkt']
------

In [9]:
# print(dictionaries[0]['data']['searchResult'].keys())

In [10]:
# print(dictionaries[0]['data']['searchResult']['poi'][0].keys())

In [11]:
print(dictionaries[0]['data']['searchResult']['poi'][0]['insights']['insights'])

[{'category': 'safety', 'tradeoff': {'insightPlace': None, 'value': 'Average crime rates', 'tagLine': 'CRIME', 'impactful': False, '__typename': 'Tradeoff'}, '__typename': 'Insight'}, {'category': 'livability', 'tradeoff': {'insightPlace': None, 'value': 'Good park access', 'tagLine': '', 'impactful': False, '__typename': 'Tradeoff'}, '__typename': 'Insight'}]

In [12]:
for dict in dictionaries:
#     print(dict['data']['searchResult']['poi'])
    for id in dict['data']['searchResult']['poi']:
#         print(id['id'])
        for i in id['insights']['insights']:
#             print(i['category'])
            if i['category'] == 'naturalLight':
                print([i['tradeoff']])
                print('----')
            else:
                None

[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has moderate sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has moderate sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has moderate sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Bright & sun drenched', 'tagLine': 'BRIGHT & SUNNY', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Limited natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has moderate sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Moderate natural light', 'tagLine': 'LESS NATURAL LIGHT', 'impactful': False, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'Bright & sun drenched', 'tagLine': 'BRIGHT & SUNNY', 'impactful': True, '__typename': 'Tradeoff'}]
----
[{'insightPlace': None, 'value': 'This apartment has limited sunlight', 'tagLine': '', 'impactful': True, '__typename': 'Tradeoff'}]
----

In [13]:
for dict in dictionaries:
#     print(dict['data']['searchResult']['poi'])
    for id in dict['data']['searchResult']['poi']:
#         print(id['id'])
        for i in id['insights']['insights']:
#             print(i['category'])
            if i['category'] == 'naturalLight':
                print(id['id'])
#                 print(id['price'])
                print(id['beds'])
                print(i['tradeoff']['value'] + f" and the rent is {id['price']}")
#             elif i['category'] != 'naturalLight' :
#                 print(f"No light info for {id['id']}, rent = {id['price']}")
        print(f"No sunlight data available for {id['id']} and the rent is {id['price']}")
    print('======')

No sunlight data available for l-l4njo7ppbf0p and the rent is 4033
m-g7pk2u6bgdl7
0
This apartment has limited sunlight and the rent is 2950
No sunlight data available for m-g7pk2u6bgdl7 and the rent is 2950
No sunlight data available for m-k641hj441qsf and the rent is 1918
No sunlight data available for m-7m7ugsdf31rv and the rent is 2035
No sunlight data available for m-5l5sbh0q5cdi and the rent is 2696
No sunlight data available for m-fuijvl2a4kvv and the rent is 2032
No sunlight data available for m-9tfhakmgmkv0 and the rent is 2027
No sunlight data available for m-f2aogop6554i and the rent is 2466
No sunlight data available for m-kde19bjr8f4m and the rent is 2030
No sunlight data available for m-eb8nghduno94 and the rent is 2031
No sunlight data available for m-gjpbcj3u72fp and the rent is 2072
No sunlight data available for m-9htcac339ik7 and the rent is 2466
No sunlight data available for m-k9oc9i9ffs63 and the rent is 2029
No sunlight data available for m-6kf4148kfddl and the rent is 2072
No sunlight data available for m-cb9vbgu5rn5 and the rent is 2071
No sunlight data available for m-au50rkfr98th and the rent is 2466
No sunlight data available for m-fo1rc16js34t and the rent is 2466
No sunlight data available for m-5ttk310iec4s and the rent is 2500
No sunlight data available for m-9p5ku13kfll7 and the rent is 2031
No sunlight data available for m-ka79svpaihfr and the rent is 2375
======
No sunlight data available for m-lblh5t3riqfu and the rent is 2100
No sunlight data available for m-skv7aqh4s5gl and the rent is 2442
No sunlight data available for m-nsn2m4kkq9uv and the rent is 2500
m-oj749aepcagp
1
This apartment has limited sunlight and the rent is 2400
No sunlight data available for m-oj749aepcagp and the rent is 2400
m-1u9m2efnbcup
1
This apartment has limited sunlight and the rent is 2400
No sunlight data available for m-1u9m2efnbcup and the rent is 2400
No sunlight data available for m-cku3fm8oskfo and the rent is 2500
m-2errkn8o62in
1
Moderate natural light and the rent is 2049
No sunlight data available for m-2errkn8o62in and the rent is 2049
m-7vhvbui4fp5j
1
Limited natural light and the rent is 2025
No sunlight data available for m-7vhvbui4fp5j and the rent is 2025
m-i151fuv22n18
1
Limited natural light and the rent is 2099
No sunlight data available for m-i151fuv22n18 and the rent is 2099
No sunlight data available for m-sul0cl5kusbl and the rent is 2000
No sunlight data available for m-993pbkgsnc3s and the rent is 2000
m-51a9boljs562
1
Limited natural light and the rent is 2300
No sunlight data available for m-51a9boljs562 and the rent is 2300
m-as4rgiinomc0
1
Moderate natural light and the rent is 2095
No sunlight data available for m-as4rgiinomc0 and the rent is 2095
m-pjck846pllqe
0
Moderate natural light and the rent is 1650
No sunlight data available for m-pjck846pllqe and the rent is 1650
m-alvdc30ctcdj
1
Moderate natural light and the rent is 2000
No sunlight data available for m-alvdc30ctcdj and the rent is 2000
No sunlight data available for m-69fm2r7uflre and the rent is 2200
No sunlight data available for m-fq59hc0hh87d and the rent is 2000
m-tq3lbh8gge9h
0
Limited natural light and the rent is 2345
No sunlight data available for m-tq3lbh8gge9h and the rent is 2345
m-6uduhgo2kok0
1
Moderate natural light and the rent is 2099
No sunlight data available for m-6uduhgo2kok0 and the rent is 2099
m-jgmipn7ma570
1
Limited natural light and the rent is 2200
No sunlight data available for m-jgmipn7ma570 and the rent is 2200
======
m-ffmjf51gcevs
1
Limited natural light and the rent is 2200
No sunlight data available for m-ffmjf51gcevs and the rent is 2200
m-5kvepkc92irh
1
Limited natural light and the rent is 2400
No sunlight data available for m-5kvepkc92irh and the rent is 2400
m-rc3ivod718i5
1
Limited natural light and the rent is 2295
No sunlight data available for m-rc3ivod718i5 and the rent is 2295
No sunlight data available for m-k9jt5mb37vfv and the rent is 2195
No sunlight data available for m-gudu0jdt7h1m and the rent is 2150
No sunlight data available for m-ho8t8dtu3k75 and the rent is 2195
No sunlight data available for m-p9epj5pvl9s9 and the rent is 2150
m-vtmqugvur0oh
1
Moderate natural light and the rent is 2250
No sunlight data available for m-vtmqugvur0oh and the rent is 2250
m-r256s2t33she
1
Limited natural light and the rent is 2199
No sunlight data available for m-r256s2t33she and the rent is 2199
m-3av8il4tckpa
1
Moderate natural light and the rent is 2500
No sunlight data available for m-3av8il4tckpa and the rent is 2500
No sunlight data available for m-8h006k5elqa5 and the rent is 1700
m-kn62klng7iho
1
Limited natural light and the rent is 2100
No sunlight data available for m-kn62klng7iho and the rent is 2100
m-da52rtlgbm82
1
Moderate natural light and the rent is 2199
No sunlight data available for m-da52rtlgbm82 and the rent is 2199
m-hmcr9o9mt0hg
1
Limited natural light and the rent is 2100
No sunlight data available for m-hmcr9o9mt0hg and the rent is 2100
No sunlight data available for m-logs01fe96gg and the rent is 2999
m-rqfceepfnus6
1
Limited natural light and the rent is 2015
No sunlight data available for m-rqfceepfnus6 and the rent is 2015
No sunlight data available for l-vloo76lhui9 and the rent is 2470
No sunlight data available for l-e0uuepcve088 and the rent is 2575
No sunlight data available for l-33135ieoeo43 and the rent is 2350
No sunlight data available for l-22radm21mj5t and the rent is 2875
======
No sunlight data available for l-mpa0bot1horv and the rent is 5000
No sunlight data available for l-niqhhmp2ao4d and the rent is 2800
No sunlight data available for l-s0q7bhrd5bm0 and the rent is 2600
l-e8a60nod7grs
0
This apartment has limited sunlight and the rent is 2877
No sunlight data available for l-e8a60nod7grs and the rent is 2877
No sunlight data available for l-ucasbmn0ub45 and the rent is 3064
No sunlight data available for l-b8bb2cfelnp4 and the rent is 3250
No sunlight data available for l-he4hrhl1avo and the rent is 4000
No sunlight data available for l-33135ieoeo43 and the rent is 2350
No sunlight data available for l-pbgo4et6bk1m and the rent is 2000
No sunlight data available for l-4dimfbh44tt1 and the rent is 2550
No sunlight data available for l-tgfdpd9ecrhe and the rent is 3100
No sunlight data available for l-nib9q9ijgoff and the rent is 3500
No sunlight data available for l-7ulf3iisd6jj and the rent is 1500
No sunlight data available for l-22radm21mj5t and the rent is 2875
No sunlight data available for l-o0rngdr2memc and the rent is 2959
l-m5skrj161t0f
1
This apartment has limited sunlight and the rent is 2500
No sunlight data available for l-m5skrj161t0f and the rent is 2500
No sunlight data available for l-69f27upectfc and the rent is 3135
No sunlight data available for l-114i1asehvc2 and the rent is 3295
No sunlight data available for l-i0241551hjsi and the rent is 2450
No sunlight data available for l-2k2qp70arkpo and the rent is 2520
======
No sunlight data available for l-mpa0bot1horv and the rent is 5000
No sunlight data available for l-niqhhmp2ao4d and the rent is 2800
No sunlight data available for l-s0q7bhrd5bm0 and the rent is 2600
l-e8a60nod7grs
0
This apartment has limited sunlight and the rent is 2877
No sunlight data available for l-e8a60nod7grs and the rent is 2877
No sunlight data available for l-ucasbmn0ub45 and the rent is 3064
No sunlight data available for l-b8bb2cfelnp4 and the rent is 3250
No sunlight data available for l-he4hrhl1avo and the rent is 4000
No sunlight data available for l-pbgo4et6bk1m and the rent is 2000
No sunlight data available for l-4dimfbh44tt1 and the rent is 2550
No sunlight data available for l-tgfdpd9ecrhe and the rent is 3100
No sunlight data available for l-nib9q9ijgoff and the rent is 3500
No sunlight data available for l-7ulf3iisd6jj and the rent is 1500
l-4glljujjq02r
1
This apartment has limited sunlight and the rent is 3000
No sunlight data available for l-4glljujjq02r and the rent is 3000
No sunlight data available for l-2j6vsj8ohsed and the rent is 3200
No sunlight data available for l-5h12jeqvbuoa and the rent is 3200
l-qj7plb01m2m0
1
This apartment has limited sunlight and the rent is 3200
No sunlight data available for l-qj7plb01m2m0 and the rent is 3200
No sunlight data available for l-in1p3ctq1l7n and the rent is 3350
No sunlight data available for l-eiahqf0jgupq and the rent is 3700
No sunlight data available for l-g4j7ikr6d4rd and the rent is 3825
m-mmkvuj8atb97
1
Limited natural light and the rent is 2895
No sunlight data available for m-mmkvuj8atb97 and the rent is 2895
======
m-d93k2e7dnm8o
1
Limited natural light and the rent is 2895
No sunlight data available for m-d93k2e7dnm8o and the rent is 2895
m-dcs5mmvka7d4
1
Limited natural light and the rent is 3300
No sunlight data available for m-dcs5mmvka7d4 and the rent is 3300
m-e9b6pkj44jc6
1
Limited natural light and the rent is 3195
No sunlight data available for m-e9b6pkj44jc6 and the rent is 3195
l-j7tp78f9d067
1
This apartment has moderate sunlight and the rent is 5750
No sunlight data available for l-j7tp78f9d067 and the rent is 5750
No sunlight data available for l-bmvc0kl7vjcv and the rent is 2000
No sunlight data available for l-pru5m07pes8v and the rent is 2950
No sunlight data available for l-tjv2dj6n654n and the rent is 2200
No sunlight data available for m-1tp44rhahjol and the rent is 2100
No sunlight data available for m-pojnp3vuvgon and the rent is 2100
No sunlight data available for m-atlajse2nlai and the rent is 2950
No sunlight data available for m-j3eccqa5vr8k and the rent is 2950
No sunlight data available for m-al6cipi17nmp and the rent is 2950
No sunlight data available for m-r26svsp2etao and the rent is 2100
No sunlight data available for m-j9ub0uspt3lj and the rent is 2950
No sunlight data available for m-us93lqi46jma and the rent is 2100
No sunlight data available for m-th3e5gmna9m1 and the rent is 2100
No sunlight data available for l-3ubttvff9u4r and the rent is 2686
No sunlight data available for l-l7ppcng5sq8v and the rent is 2542
No sunlight data available for l-mh9qfjcn1r9e and the rent is 2200
No sunlight data available for m-h21bsjgo95b0 and the rent is 2150
======
No sunlight data available for m-bfdnogc97rm2 and the rent is 2390
No sunlight data available for l-566a13ifc12a and the rent is 2125
No sunlight data available for l-iskt4hbdggaj and the rent is 2000
No sunlight data available for l-inje6git2s3 and the rent is 4003
No sunlight data available for l-av061bbfimlb and the rent is 4018
l-47nnhcpcrano
1
This apartment has limited sunlight and the rent is 3764
No sunlight data available for l-47nnhcpcrano and the rent is 3764
No sunlight data available for l-b4hoklgqau8l and the rent is 4350
l-qh300dtif0ah
1
This apartment has limited sunlight and the rent is 3545
No sunlight data available for l-qh300dtif0ah and the rent is 3545
No sunlight data available for l-8jmgtcelkqau and the rent is 2857
No sunlight data available for l-475vglb54oai and the rent is 3725
No sunlight data available for l-bcukcl31jkl0 and the rent is 2995
No sunlight data available for l-rv33e2rues2r and the rent is 2000
No sunlight data available for l-7471p5da5s4g and the rent is 2150
No sunlight data available for m-dnfmn18m8ae7 and the rent is 2250
No sunlight data available for l-nqq3vjtc4n9k and the rent is 3550
No sunlight data available for l-c0dm8dl8fnab and the rent is 3238
No sunlight data available for l-ivltrfkc5kmm and the rent is 2500
l-skpvkqbbue9j
1
This apartment has moderate sunlight and the rent is 4000
No sunlight data available for l-skpvkqbbue9j and the rent is 4000
No sunlight data available for l-jm1qrmj40hlg and the rent is 3195
No sunlight data available for l-1ivun56qi299 and the rent is 5585
======
No sunlight data available for l-srbn5ucmgbc0 and the rent is 3683
No sunlight data available for l-5mt2g1dct183 and the rent is 3697
No sunlight data available for l-vkhdtnq6trpi and the rent is 3688
No sunlight data available for m-bnkfi8dmj45k and the rent is 2100
No sunlight data available for m-qddqkcgm4vu0 and the rent is 2600
No sunlight data available for m-2jnojj5ivupc and the rent is 3000
No sunlight data available for m-ioml7upjj0nf and the rent is 2100
No sunlight data available for m-1a68bqniv8f5 and the rent is 2600
No sunlight data available for m-52krgvmtanfq and the rent is 2600
No sunlight data available for m-3h2b7f9f864 and the rent is 2950
No sunlight data available for m-mllprmn7u2q and the rent is 2100
No sunlight data available for m-175u8hpq13uk and the rent is 2600
No sunlight data available for m-i7753l1falmj and the rent is 2600
No sunlight data available for m-39adoidr9t7j and the rent is 2950
No sunlight data available for m-qako0aep671j and the rent is 2950
No sunlight data available for m-fhjftpbgko0c and the rent is 2291
No sunlight data available for m-lkaovhe3vi2k and the rent is 2836
No sunlight data available for m-6jj3p09j1oaa and the rent is 3273
No sunlight data available for m-e9oadqrasp4k and the rent is 2945
No sunlight data available for m-4g38orid0ttu and the rent is 3491
======
No sunlight data available for m-4g38orid0ttu and the rent is 3491
No sunlight data available for m-8ac4uoe1n8ec and the rent is 3600
l-af04hjn8ih6a
1
This apartment has moderate sunlight and the rent is 4500
No sunlight data available for l-af04hjn8ih6a and the rent is 4500
l-e23oh50jf3js
1
This apartment has limited sunlight and the rent is 2500
No sunlight data available for l-e23oh50jf3js and the rent is 2500
No sunlight data available for l-q69hi8o4fh1u and the rent is 2700
No sunlight data available for l-o3ke9d887v04 and the rent is 3108
No sunlight data available for m-dlb79be872u9 and the rent is 2500
l-5sr3mraftvdo
1
This apartment has limited sunlight and the rent is 5595
No sunlight data available for l-5sr3mraftvdo and the rent is 5595
No sunlight data available for l-9417psnrdkqb and the rent is 3600
m-oc27u40tqu3k
1
Limited natural light and the rent is 2350
No sunlight data available for m-oc27u40tqu3k and the rent is 2350
No sunlight data available for m-6aoa0jitd5d7 and the rent is 2600
No sunlight data available for l-ue6jib37qqnf and the rent is 3500
No sunlight data available for l-94a2gjl0u1g1 and the rent is 3050
No sunlight data available for l-88virisvsmsi and the rent is 3100
m-ha3scum2sgo1
1
Moderate natural light and the rent is 3300
No sunlight data available for m-ha3scum2sgo1 and the rent is 3300
No sunlight data available for m-3nne3j20j5cb and the rent is 2400
No sunlight data available for m-aopat6l3s9ej and the rent is 2350
No sunlight data available for m-59oq08252jg8 and the rent is 2200
No sunlight data available for l-jmve9n9ak98q and the rent is 3075
No sunlight data available for l-eocm9b7e0ci1 and the rent is 2500
======
No sunlight data available for m-gt9li0q09upv and the rent is 3138
No sunlight data available for m-440k5u8m85op and the rent is 2920
No sunlight data available for m-i7lj3vg57hhp and the rent is 2730
No sunlight data available for l-g8kqq3bhsigp and the rent is 2400
No sunlight data available for l-lf4rbiapfuqo and the rent is 2800
No sunlight data available for l-mfg3np6mqcgh and the rent is 1919
m-6647ng7l2sgm
1
Limited natural light and the rent is 2590
No sunlight data available for m-6647ng7l2sgm and the rent is 2590
m-8rdcg1kqnjh8
1
Limited natural light and the rent is 2590
No sunlight data available for m-8rdcg1kqnjh8 and the rent is 2590
m-k53u06j4180
1
This apartment has limited sunlight and the rent is 1950
No sunlight data available for m-k53u06j4180 and the rent is 1950
No sunlight data available for m-herq8clovjk4 and the rent is 1950
m-qedem2h2qs8t
1
Limited natural light and the rent is 1700
No sunlight data available for m-qedem2h2qs8t and the rent is 1700
No sunlight data available for m-j80igb3rniuk and the rent is 1900
No sunlight data available for m-4sbq6mdg0dml and the rent is 3200
No sunlight data available for m-fhhsdl6rdr3b and the rent is 2850
No sunlight data available for m-f918uuvp2nuc and the rent is 2800
No sunlight data available for m-c4it0pjromg and the rent is 3200
No sunlight data available for m-msf6rb8peb05 and the rent is 2830
No sunlight data available for m-cidleafi7fv7 and the rent is 2830
No sunlight data available for l-b65oi9p4kfn6 and the rent is 2800
No sunlight data available for l-a8m7jtmn1l8g and the rent is 2800
======
m-ngt4ph8udkmq
1
Moderate natural light and the rent is 2125
No sunlight data available for m-ngt4ph8udkmq and the rent is 2125
m-jmtr0spu4jut
1
Limited natural light and the rent is 2000
No sunlight data available for m-jmtr0spu4jut and the rent is 2000
No sunlight data available for m-dvmglep3gq88 and the rent is 2750
No sunlight data available for l-4m0q83824jh4 and the rent is 4050
No sunlight data available for l-3ruktjkghna8 and the rent is 2250
m-84sipv8lrh8v
0
Moderate natural light and the rent is 1650
No sunlight data available for m-84sipv8lrh8v and the rent is 1650
No sunlight data available for m-qmam6gq4qni9 and the rent is 2250
l-qp91auide8ca
1
This apartment has limited sunlight and the rent is 3200
No sunlight data available for l-qp91auide8ca and the rent is 3200
No sunlight data available for l-8eu4lc6s5t8o and the rent is 2800
m-jag808dc459v
1
Limited natural light and the rent is 2149
No sunlight data available for m-jag808dc459v and the rent is 2149
No sunlight data available for l-9f5kcehflfmu and the rent is 2700
l-pngptb07ovrd
1
This apartment has limited sunlight and the rent is 2900
No sunlight data available for l-pngptb07ovrd and the rent is 2900
m-vpduu8qvbhim
1
Limited natural light and the rent is 2050
No sunlight data available for m-vpduu8qvbhim and the rent is 2050
No sunlight data available for m-ts3f6uqiskp3 and the rent is 2300
m-19loqn2udrop
1
Moderate natural light and the rent is 2825
No sunlight data available for m-19loqn2udrop and the rent is 2825
m-7l0sn2vijjtq
1
Limited natural light and the rent is 2790
No sunlight data available for m-7l0sn2vijjtq and the rent is 2790
No sunlight data available for l-a3m6i3kr44j6 and the rent is 2800
l-p6sepvkpkl3e
1
This apartment has limited sunlight and the rent is 3400
No sunlight data available for l-p6sepvkpkl3e and the rent is 3400
No sunlight data available for m-n6hdierg196s and the rent is 2625
No sunlight data available for m-tgv98j1easj5 and the rent is 2625
======
No sunlight data available for m-5dpr3rp5de9l and the rent is 2625
No sunlight data available for m-c37itnq8l7r3 and the rent is 2550
m-cppnnes2qq7u
1
Bright & sun drenched and the rent is 2050
No sunlight data available for m-cppnnes2qq7u and the rent is 2050
No sunlight data available for l-aaum7dk0s54s and the rent is 4750
No sunlight data available for m-mosqba1euac8 and the rent is 2994
No sunlight data available for m-j1imhv5kuv4m and the rent is 2994
l-o4a7mm1t56a2
1
This apartment has limited sunlight and the rent is 2450
No sunlight data available for l-o4a7mm1t56a2 and the rent is 2450
No sunlight data available for m-qu0h333unbdg and the rent is 2600
No sunlight data available for l-nrca98729k7u and the rent is 2795
No sunlight data available for l-614av50ij5cb and the rent is 2250
No sunlight data available for l-m1cdv0oquami and the rent is 2500
No sunlight data available for l-ico56tofpl8q and the rent is 2400
No sunlight data available for l-dtlgbj17f16j and the rent is 900
No sunlight data available for m-qhhbu9fogn0e and the rent is 2450
No sunlight data available for m-s2cdf4ftst12 and the rent is 2450
m-as7sdoe4223s
1
This apartment has limited sunlight and the rent is 1995
No sunlight data available for m-as7sdoe4223s and the rent is 1995
m-du28k1ukeoap
1
This apartment has limited sunlight and the rent is 1995
No sunlight data available for m-du28k1ukeoap and the rent is 1995
No sunlight data available for l-1cumekhger73 and the rent is 3395
No sunlight data available for l-tdbjur5f7qck and the rent is 3000

In [14]:
ids = []
zipcode = []
unit_number = []
beds = []
size = []
rents = []
light_cat = []
lights = []

for dictionary in dictionaries:
    for id in dictionary['data']['searchResult']['poi']:
        for insight in id['insights']['insights']:
            if insight['category'] == 'naturalLight':
                ids.append(id['id'])
                zipcode.append(id['addressDetails']['zipcode'])
                unit_number.append(id['addressDetails']['unitNumber'])
                beds.append(id['beds'])
                size.append(id['area'])
                rents.append(id['price'])
                light_cat.append(insight['tradeoff']['value'])
                lights.append(insight['tradeoff']['value'] + f" and the rent is {id['price']}")
        if len(id['insights']['insights']) == 0 or all(insight['category'] != 'naturalLight' for insight in id['insights']['insights']):
            ids.append(id['id'])
            zipcode.append(id['addressDetails']['zipcode'])
            unit_number.append(id['addressDetails']['unitNumber'])
            beds.append(id['beds'])
            size.append(id['area'])
            rents.append(id['price'])
            light_cat.append(f"No sunlight")
            lights.append(f"No sunlight data available and the rent is {id['price']}")

## Pre-processing apartment listings with sun exposure details

In [15]:
data = {
    'listing_path': ids,
    'location': zipcode,
    'unit_number': unit_number,
    'beds': beds,
    'size':size,
    'rent': rents,
    'sun_exposure_cat': light_cat,
    'sun_exposure': lights
}

df_sun_exposure = pd.DataFrame(data)

In [16]:
df_sun_exposure.head()

,listing_path,location,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight,No sunlight data available and the rent is 4033
1,m-g7pk2u6bgdl7,11216,21,0,680.0,2950,This apartment has limited sunlight,This apartment has limited sunlight and the re...
2,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight,No sunlight data available and the rent is 1918
3,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight,No sunlight data available and the rent is 2035
4,m-5l5sbh0q5cdi,11216,1A,0,0.0,2696,No sunlight,No sunlight data available and the rent is 2696

In [17]:
df_sun_exposure.sort_values(by = 'rent',ascending =False).sort_values(by = 'location',ascending =True)

,listing_path,location,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure
35,m-69fm2r7uflre,11203,6B,1,550.0,2200,No sunlight,No sunlight data available and the rent is 2200
103,l-j7tp78f9d067,11205,1,1,1471.0,5750,This apartment has moderate sunlight,This apartment has moderate sunlight and the r...
101,m-dcs5mmvka7d4,11205,3F,1,0.0,3300,Limited natural light,Limited natural light and the rent is 3300
138,l-jm1qrmj40hlg,11205,3A,1,NaN,3195,No sunlight,No sunlight data available and the rent is 3195
102,m-e9b6pkj44jc6,11205,3A,1,0.0,3195,Limited natural light,Limited natural light and the rent is 3195
...,...,...,...,...,...,...,...,...
96,l-in1p3ctq1l7n,11238,3,1,700.0,3350,No sunlight,No sunlight data available and the rent is 3350
143,m-bnkfi8dmj45k,11238,1F,0,9999.0,2100,No sunlight,No sunlight data available and the rent is 2100
112,m-r26svsp2etao,11238,304,0,9999.0,2100,No sunlight,No sunlight data available and the rent is 2100
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight,No sunlight data available and the rent is 4033
66,l-he4hrhl1avo,11238,306,1,NaN,4000,No sunlight,No sunlight data available and the rent is 4000

In [18]:
df_sun_exposure.dtypes

listing_path         object
location             object
unit_number          object
beds                  int64
size                float64
rent                  int64
sun_exposure_cat     object
sun_exposure         object
dtype: object

In [19]:
unique_values = df_sun_exposure['sun_exposure_cat'].unique()

# Print the unique values
for value in unique_values:
    print(value)

No sunlight
This apartment has limited sunlight
Moderate natural light
Limited natural light
This apartment has moderate sunlight
Bright & sun drenched

In [20]:
label_mapping = {
    'No sunlight': 'No sunlight data',
    'nan':'No sunlight data',
    'Limited natural light': 'Limited natural light',
    'This apartment has limited sunlight': 'Limited natural light',
    'This apartment has moderate sunlight': 'Moderate sunlight',
    'Moderate natural light':'Moderate sunlight',
    'Bright & sun drenched':'Bright & sun drenched',
    
}

# Update the values in the column using the map() method
df_sun_exposure['sun_exposure_cat'] = df_sun_exposure['sun_exposure_cat'].map(label_mapping)

# The values in the 'your_column_name' column will be updated with the new labels

# Example: Printing the updated column
print(df_sun_exposure['sun_exposure_cat'])

0           No sunlight data
1      Limited natural light
2           No sunlight data
3           No sunlight data
4           No sunlight data
               ...
255    Bright & sun drenched
256    Limited natural light
257         No sunlight data
258         No sunlight data
259         No sunlight data
Name: sun_exposure_cat, Length: 260, dtype: object

In [21]:
df_sun_exposure

,listing_path,location,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight data,No sunlight data available and the rent is 4033
1,m-g7pk2u6bgdl7,11216,21,0,680.0,2950,Limited natural light,This apartment has limited sunlight and the re...
2,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight data,No sunlight data available and the rent is 1918
3,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight data,No sunlight data available and the rent is 2035
4,m-5l5sbh0q5cdi,11216,1A,0,0.0,2696,No sunlight data,No sunlight data available and the rent is 2696
...,...,...,...,...,...,...,...,...
255,m-t8p0q78tlp5k,11221,A2,0,0.0,3449,Bright & sun drenched,Bright & sun drenched and the rent is 3449
256,m-a3poj9qc2mh8,11221,3F,1,9999.0,2250,Limited natural light,This apartment has limited sunlight and the re...
257,l-40dte2cunttt,11221,3R,1,NaN,2400,No sunlight data,No sunlight data available and the rent is 2400
258,l-sk18vv1pjmct,11221,2,1,NaN,2700,No sunlight data,No sunlight data available and the rent is 2700
259,m-9en3gqdfipkt,11221,6B,1,0.0,2292,No sunlight data,No sunlight data available and the rent is 2292

In [22]:
df_sun_exposure['floor'] = df_sun_exposure['unit_number'].apply(lambda x: re.findall(r'\d', x)[0] if re.findall(r'\d', x) else None)

In [23]:
df_sun_exposure

,listing_path,location,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight data,No sunlight data available and the rent is 4033,5
1,m-g7pk2u6bgdl7,11216,21,0,680.0,2950,Limited natural light,This apartment has limited sunlight and the re...,2
2,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight data,No sunlight data available and the rent is 1918,None
3,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight data,No sunlight data available and the rent is 2035,2
4,m-5l5sbh0q5cdi,11216,1A,0,0.0,2696,No sunlight data,No sunlight data available and the rent is 2696,1
...,...,...,...,...,...,...,...,...,...
255,m-t8p0q78tlp5k,11221,A2,0,0.0,3449,Bright & sun drenched,Bright & sun drenched and the rent is 3449,2
256,m-a3poj9qc2mh8,11221,3F,1,9999.0,2250,Limited natural light,This apartment has limited sunlight and the re...,3
257,l-40dte2cunttt,11221,3R,1,NaN,2400,No sunlight data,No sunlight data available and the rent is 2400,3
258,l-sk18vv1pjmct,11221,2,1,NaN,2700,No sunlight data,No sunlight data available and the rent is 2700,2
259,m-9en3gqdfipkt,11221,6B,1,0.0,2292,No sunlight data,No sunlight data available and the rent is 2292,6

In [24]:
df_sun_exposure.to_csv('bk_sun_exposure.csv', index = False)

# Reading in Median Income Data for Brooklyn Neighbourhoods

In [25]:
df_bk_income = pd.read_csv('brooklyn_median_income.csv')

In [26]:
df_bk_income

,BoroName,Neighbourhood,Zipcode,Median Household Income\n(American Community Survey (ACS) 5-Year Estimates from 2015-2019),Predominant Group\n(American Community Survey (ACS) 5-Year Estimates from 2015-2019)\n(Predominant group refers to the racial/ethnic group that has the highest percentage in the neighborhood),Percentage\n(The percentage values refer to the percentage of the total population in each neighborhood that belongs to the predominant group listed),Unnamed: 6
0,Brooklyn,Bath Beach,11214,"$51,380",Asian People,0.44,NaN
1,Brooklyn,Canarsie,11236,"$67,382",White People,0.61,NaN
2,Brooklyn,Bedford-Stuyvesant (East),"11213, 11216, 11233","$56,831",Black People,0.82,NaN
3,Brooklyn,Bedford-Stuyvesant (West),"11206, 11216, 11221, 11233","$51,759",Black People,0.83,NaN
4,Brooklyn,Crown Heights (North),"11213, 11216, 11225, 11233","$53,529",Asian People,0.47,NaN
...,...,...,...,...,...,...,...
59,Brooklyn,Sunset Park (East)-Borough Park (West),"11219, 11220","$56,270",Hispanic/Latino People,0.44,NaN
60,Brooklyn,Sunset Park (West),"11220, 11232","$52,651",Hispanic/Latino People,0.64,NaN
61,Brooklyn,The Evergreens Cemetery,"11207, 11208",NaN,Hispanic/Latino People,0.57,NaN
62,Brooklyn,Williamsburg,"11206, 11211, 11249","$65,196",Hispanic/Latino People,0.42,NaN
63,Brooklyn,Windsor Terrace-South Slope,"11215, 11218","$88,212",White People,0.61,NaN

## Pre-processing Brooklyn Median Income Data

In [27]:
df_bk_income.columns = df_bk_income.columns.str.lower() #convert column names to lowercase

In [28]:
df_bk_income

,boroname,neighbourhood,zipcode,median household income\n(american community survey (acs) 5-year estimates from 2015-2019),predominant group\n(american community survey (acs) 5-year estimates from 2015-2019)\n(predominant group refers to the racial/ethnic group that has the highest percentage in the neighborhood),percentage\n(the percentage values refer to the percentage of the total population in each neighborhood that belongs to the predominant group listed),unnamed: 6
0,Brooklyn,Bath Beach,11214,"$51,380",Asian People,0.44,NaN
1,Brooklyn,Canarsie,11236,"$67,382",White People,0.61,NaN
2,Brooklyn,Bedford-Stuyvesant (East),"11213, 11216, 11233","$56,831",Black People,0.82,NaN
3,Brooklyn,Bedford-Stuyvesant (West),"11206, 11216, 11221, 11233","$51,759",Black People,0.83,NaN
4,Brooklyn,Crown Heights (North),"11213, 11216, 11225, 11233","$53,529",Asian People,0.47,NaN
...,...,...,...,...,...,...,...
59,Brooklyn,Sunset Park (East)-Borough Park (West),"11219, 11220","$56,270",Hispanic/Latino People,0.44,NaN
60,Brooklyn,Sunset Park (West),"11220, 11232","$52,651",Hispanic/Latino People,0.64,NaN
61,Brooklyn,The Evergreens Cemetery,"11207, 11208",NaN,Hispanic/Latino People,0.57,NaN
62,Brooklyn,Williamsburg,"11206, 11211, 11249","$65,196",Hispanic/Latino People,0.42,NaN
63,Brooklyn,Windsor Terrace-South Slope,"11215, 11218","$88,212",White People,0.61,NaN

In [29]:
df_bk_income['zipcode'] = df_bk_income['zipcode'].str.split(', ')
df_bk_income = df_bk_income.explode('zipcode')

df_bk_income.reset_index(drop=True, inplace=True)

In [30]:
df_bk_income.head()

,boroname,neighbourhood,zipcode,median household income\n(american community survey (acs) 5-year estimates from 2015-2019),predominant group\n(american community survey (acs) 5-year estimates from 2015-2019)\n(predominant group refers to the racial/ethnic group that has the highest percentage in the neighborhood),percentage\n(the percentage values refer to the percentage of the total population in each neighborhood that belongs to the predominant group listed),unnamed: 6
0,Brooklyn,Bath Beach,11214,"$51,380",Asian People,0.44,NaN
1,Brooklyn,Canarsie,11236,"$67,382",White People,0.61,NaN
2,Brooklyn,Bedford-Stuyvesant (East),11213,"$56,831",Black People,0.82,NaN
3,Brooklyn,Bedford-Stuyvesant (East),11216,"$56,831",Black People,0.82,NaN
4,Brooklyn,Bedford-Stuyvesant (East),11233,"$56,831",Black People,0.82,NaN

# Pre-processing ACS Household Living Data from Census Reporter

In [31]:
with open('/Users/ligeaalexander/Desktop/Developer/Project-2/acs2021_5yr_B09021.json', 'r') as file:
        bk_pop_living = json.load(file)
print(bk_pop_living)

{'release': {'id': 'acs2021_5yr', 'years': '2017-2021', 'name': 'ACS 2021 5-year'}, 'tables': {'B09021': {'title': 'Living Arrangements of Adults 18 Years and Over by Age', 'universe': 'Population 18 Years and Over in Households', 'denominator_column_id': 'B09021001', 'columns': {'B09021001': {'name': 'Total:', 'indent': 0}, 'B09021002': {'name': 'Lives alone', 'indent': 1}, 'B09021003': {'name': 'Householder living with spouse or spouse of householder', 'indent': 1}, 'B09021004': {'name': 'Householder living with unmarried partner or unmarried partner of householder', 'indent': 1}, 'B09021005': {'name': 'Child of householder', 'indent': 1}, 'B09021006': {'name': 'Other relatives', 'indent': 1}, 'B09021007': {'name': 'Other nonrelatives', 'indent': 1}, 'B09021008': {'name': '18 to 34 years:', 'indent': 1}, 'B09021009': {'name': 'Lives alone', 'indent': 2}, 'B09021010': {'name': 'Householder living with spouse or spouse of householder', 'indent': 2}, 'B09021011': {'name': 'Householder living with unmarried partner or unmarried partner of householder', 'indent': 2}, 'B09021012': {'name': 'Child of householder', 'indent': 2}, 'B09021013': {'name': 'Other relatives', 'indent': 2}, 'B09021014': {'name': 'Other nonrelatives', 'indent': 2}, 'B09021015': {'name': '35 to 64 years:', 'indent': 1}, 'B09021016': {'name': 'Lives alone', 'indent': 2}, 'B09021017': {'name': 'Householder living with spouse or spouse of householder', 'indent': 2}, 'B09021018': {'name': 'Householder living with unmarried partner or unmarried partner of householder', 'indent': 2}, 'B09021019': {'name': 'Child of householder', 'indent': 2}, 'B09021020': {'name': 'Other relatives', 'indent': 2}, 'B09021021': {'name': 'Other nonrelatives', 'indent': 2}, 'B09021022': {'name': '65 years and over:', 'indent': 1}, 'B09021023': {'name': 'Lives alone', 'indent': 2}, 'B09021024': {'name': 'Householder living with spouse or spouse of householder', 'indent': 2}, 'B09021025': {'name': 'Householder living with unmarried partner or unmarried partner of householder', 'indent': 2}, 'B09021026': {'name': 'Child of householder', 'indent': 2}, 'B09021027': {'name': 'Other relatives', 'indent': 2}, 'B09021028': {'name': 'Other nonrelatives', 'indent': 2}}}}}

In [32]:
print(bk_pop_living.keys())

dict_keys(['release', 'tables'])

In [33]:
df_acs = pd.read_csv('acs2021_5yr_B09021_86000US11230.csv')

In [34]:
df_acs.head()

,geoid,Zipcode,Total,"B09021001, Error",Lives alone,"B09021002, Error",Householder living with spouse or spouse of householder,"B09021003, Error",Householder living with unmarried partner or unmarried partner of householder,"B09021004, Error",...,Householder living with spouse or spouse of householder.3,"B09021024, Error",Householder living with unmarried partner or unmarried partner of householder.3,"B09021025, Error",Child of householder.3,"B09021026, Error",Other relatives.3,"B09021027, Error",Other nonrelatives.3,"B09021028, Error"
0,06000US3604710022,"Brooklyn borough, Kings County, NY",2049635,1837,288737,3751,743459,7989,127366,3926,...,147373,3369,6937,727,1495,368,98707,2610,12970,1158
1,86000US07002,7002,54196,906,8157,832,23770,1084,2543,533,...,4417,618,127,73,0,31,2070,331,272,156
2,86000US07305,7305,53225,1791,7248,755,18997,1622,3247,844,...,3113,601,248,126,16,25,3136,549,152,114
3,86000US11101,11101,27405,1402,6451,749,10152,1089,2697,543,...,1016,372,61,95,0,27,411,172,21,21
4,86000US11201,11201,52600,1708,11693,845,22795,1370,6973,741,...,3219,466,251,121,0,30,899,239,71,61

In [35]:
# with open('acs2021_5yr_B09021.json', 'r') as file:
#         acs_labels = json.load(file)
# print(acs_labels)

In [36]:
# acs_labels['tables']['B09021']['columns'].values()

In [37]:
# labels = pd.DataFrame(acs_labels['tables']['B09021']['columns'])

In [38]:
# labels

In [39]:
# df_acs.columns

In [40]:
# labels.to_csv('acs_labels.csv', index = False)

In [41]:
df_acs = pd.read_csv('acs2021_5yr_B09021_86000US11230.csv')

In [42]:
df_acs.head()

,geoid,Zipcode,Total,"B09021001, Error",Lives alone,"B09021002, Error",Householder living with spouse or spouse of householder,"B09021003, Error",Householder living with unmarried partner or unmarried partner of householder,"B09021004, Error",...,Householder living with spouse or spouse of householder.3,"B09021024, Error",Householder living with unmarried partner or unmarried partner of householder.3,"B09021025, Error",Child of householder.3,"B09021026, Error",Other relatives.3,"B09021027, Error",Other nonrelatives.3,"B09021028, Error"
0,06000US3604710022,"Brooklyn borough, Kings County, NY",2049635,1837,288737,3751,743459,7989,127366,3926,...,147373,3369,6937,727,1495,368,98707,2610,12970,1158
1,86000US07002,7002,54196,906,8157,832,23770,1084,2543,533,...,4417,618,127,73,0,31,2070,331,272,156
2,86000US07305,7305,53225,1791,7248,755,18997,1622,3247,844,...,3113,601,248,126,16,25,3136,549,152,114
3,86000US11101,11101,27405,1402,6451,749,10152,1089,2697,543,...,1016,372,61,95,0,27,411,172,21,21
4,86000US11201,11201,52600,1708,11693,845,22795,1370,6973,741,...,3219,466,251,121,0,30,899,239,71,61

In [43]:
df_acs.columns = df_acs.columns.str.lower()

In [44]:
df_acs.head(3)

,geoid,zipcode,total,"b09021001, error",lives alone,"b09021002, error",householder living with spouse or spouse of householder,"b09021003, error",householder living with unmarried partner or unmarried partner of householder,"b09021004, error",...,householder living with spouse or spouse of householder.3,"b09021024, error",householder living with unmarried partner or unmarried partner of householder.3,"b09021025, error",child of householder.3,"b09021026, error",other relatives.3,"b09021027, error",other nonrelatives.3,"b09021028, error"
0,06000US3604710022,"Brooklyn borough, Kings County, NY",2049635,1837,288737,3751,743459,7989,127366,3926,...,147373,3369,6937,727,1495,368,98707,2610,12970,1158
1,86000US07002,7002,54196,906,8157,832,23770,1084,2543,533,...,4417,618,127,73,0,31,2070,331,272,156
2,86000US07305,7305,53225,1791,7248,755,18997,1622,3247,844,...,3113,601,248,126,16,25,3136,549,152,114

In [45]:
df_acs = df_acs.iloc[1:]

In [46]:
df_acs.head()

,geoid,zipcode,total,"b09021001, error",lives alone,"b09021002, error",householder living with spouse or spouse of householder,"b09021003, error",householder living with unmarried partner or unmarried partner of householder,"b09021004, error",...,householder living with spouse or spouse of householder.3,"b09021024, error",householder living with unmarried partner or unmarried partner of householder.3,"b09021025, error",child of householder.3,"b09021026, error",other relatives.3,"b09021027, error",other nonrelatives.3,"b09021028, error"
1,86000US07002,7002,54196,906,8157,832,23770,1084,2543,533,...,4417,618,127,73,0,31,2070,331,272,156
2,86000US07305,7305,53225,1791,7248,755,18997,1622,3247,844,...,3113,601,248,126,16,25,3136,549,152,114
3,86000US11101,11101,27405,1402,6451,749,10152,1089,2697,543,...,1016,372,61,95,0,27,411,172,21,21
4,86000US11201,11201,52600,1708,11693,845,22795,1370,6973,741,...,3219,466,251,121,0,30,899,239,71,61
5,86000US11203,11203,62279,2066,8376,590,18095,1065,2343,535,...,5640,583,283,110,47,34,4271,503,477,195

In [47]:
df_acs.reset_index(drop = True, inplace = True)

In [48]:
df_acs[df_acs.zipcode == '7002']

,geoid,zipcode,total,"b09021001, error",lives alone,"b09021002, error",householder living with spouse or spouse of householder,"b09021003, error",householder living with unmarried partner or unmarried partner of householder,"b09021004, error",...,householder living with spouse or spouse of householder.3,"b09021024, error",householder living with unmarried partner or unmarried partner of householder.3,"b09021025, error",child of householder.3,"b09021026, error",other relatives.3,"b09021027, error",other nonrelatives.3,"b09021028, error"
0,86000US07002,7002,54196,906,8157,832,23770,1084,2543,533,...,4417,618,127,73,0,31,2070,331,272,156

In [49]:
df_acs.columns

Index(['geoid', 'zipcode', 'total', 'b09021001, error', 'lives alone',
       'b09021002, error',
       'householder living with spouse or spouse of householder',
       'b09021003, error',
       'householder living with unmarried partner or unmarried partner of householder',
       'b09021004, error', 'child of householder', 'b09021005, error',
       'other relatives', 'b09021006, error', 'other nonrelatives',
       'b09021007, error', '18 to 34 years:', 'b09021008, error',
       'lives alone.1', 'b09021009, error',
       'householder living with spouse or spouse of householder.1',
       'b09021010, error',
       'householder living with unmarried partner or unmarried partner of householder.1',
       'b09021011, error', 'child of householder.1', 'b09021012, error',
       'other relatives.1', 'b09021013, error', 'other nonrelatives.1',
       'b09021014, error', '35 to 64 years:', 'b09021015, error',
       'lives alone.2', 'b09021016, error',
       'householder living with spouse or spouse of householder.2',
       'b09021017, error',
       'householder living with unmarried partner or unmarried partner of householder.2',
       'b09021018, error', 'child of householder.2', 'b09021019, error',
       'other relatives.2', 'b09021020, error', 'other nonrelatives.2',
       'b09021021, error', '65 years and over:', 'b09021022, error',
       'lives alone.3', 'b09021023, error',
       'householder living with spouse or spouse of householder.3',
       'b09021024, error',
       'householder living with unmarried partner or unmarried partner of householder.3',
       'b09021025, error', 'child of householder.3', 'b09021026, error',
       'other relatives.3', 'b09021027, error', 'other nonrelatives.3',
       'b09021028, error'],
      dtype='object')

In [50]:
df_acs.columns = [re.sub(r'\W+', '', col.strip().lower()) if 'error' in col.lower() else col for col in df_acs.columns]
filtered_columns = [col for col in df_acs.columns if 'error' not in col.lower()]

In [51]:
df_acs_filtered = df_acs[filtered_columns]

In [52]:
df_acs_filtered.head()

,geoid,zipcode,total,lives alone,householder living with spouse or spouse of householder,householder living with unmarried partner or unmarried partner of householder,child of householder,other relatives,other nonrelatives,18 to 34 years:,...,child of householder.2,other relatives.2,other nonrelatives.2,65 years and over:,lives alone.3,householder living with spouse or spouse of householder.3,householder living with unmarried partner or unmarried partner of householder.3,child of householder.3,other relatives.3,other nonrelatives.3
0,86000US07002,7002,54196,8157,23770,2543,7490,9911,2325,15402,...,1164,5725,1185,10084,3198,4417,127,0,2070,272
1,86000US07305,7305,53225,7248,18997,3247,8626,12269,2838,17113,...,1598,5916,1368,9730,3065,3113,248,16,3136,152
2,86000US11101,11101,27405,6451,10152,2697,1617,3384,3104,11862,...,279,1970,889,2523,1014,1016,61,0,411,21
3,86000US11201,11201,52600,11693,22795,6973,2394,4719,4026,18784,...,354,2628,833,7503,3063,3219,251,0,899,71
4,86000US11203,11203,62279,8376,18095,2343,12599,17988,2878,17409,...,4033,9132,1323,14080,3362,5640,283,47,4271,477

# Analysis and Visualization

In [53]:
selected_zipcodes = ['11215', '11217', '11225', '11218','11226','11238']

In [54]:
df_acs_selected_zipcodes = df_acs_filtered[df_acs_filtered['zipcode'].isin(selected_zipcodes)]

In [55]:
df_acs_selected_zipcodes.reset_index(drop = True, inplace = True)

In [56]:
df_acs_selected_zipcodes

,geoid,zipcode,total,lives alone,householder living with spouse or spouse of householder,householder living with unmarried partner or unmarried partner of householder,child of householder,other relatives,other nonrelatives,18 to 34 years:,...,child of householder.2,other relatives.2,other nonrelatives.2,65 years and over:,lives alone.3,householder living with spouse or spouse of householder.3,householder living with unmarried partner or unmarried partner of householder.3,child of householder.3,other relatives.3,other nonrelatives.3
0,86000US11215,11215,56580,7522,29844,5705,3361,4359,5789,16567,...,672,2357,1552,7889,1684,4468,243,11,1104,379
1,86000US11217,11217,33427,6388,12215,4630,2308,3794,4092,12560,...,454,2017,1163,4482,1361,1823,169,34,879,216
2,86000US11218,11218,54613,6965,25500,2770,7418,8187,3773,15461,...,1474,3742,1260,9352,2521,3738,200,30,2618,245
3,86000US11225,11225,48984,8978,12766,3832,6997,10241,6170,18374,...,1815,4358,1291,9414,3194,2605,156,45,3121,293
4,86000US11226,11226,78956,11590,20624,4652,13136,20512,8442,28997,...,3213,10028,2535,12353,3147,3543,250,42,4913,458
5,86000US11238,11238,47998,9299,16884,5428,3323,4747,8317,19005,...,1062,2441,1544,6352,2182,2120,272,7,1421,350

In [57]:
df_bk_income_selected = df_bk_income[df_bk_income['zipcode'].isin(selected_zipcodes)]

In [58]:
df_bk_income_selected.reset_index(drop = True, inplace = True)

In [59]:
df_bk_income_selected.head()

,boroname,neighbourhood,zipcode,median household income\n(american community survey (acs) 5-year estimates from 2015-2019),predominant group\n(american community survey (acs) 5-year estimates from 2015-2019)\n(predominant group refers to the racial/ethnic group that has the highest percentage in the neighborhood),percentage\n(the percentage values refer to the percentage of the total population in each neighborhood that belongs to the predominant group listed),unnamed: 6
0,Brooklyn,Crown Heights (North),11225,"$53,529",Asian People,0.47,NaN
1,Brooklyn,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,11217,"$88,206",White People,0.64,NaN
2,Brooklyn,Carroll Gardens-Cobble Hill-Gowanus-Red Hook,11215,"$88,206",White People,0.64,NaN
3,Brooklyn,Clinton Hill,11238,"$89,431",Black People,0.51,NaN
4,Brooklyn,Crown Heights (South),11225,"$56,831",Black People,0.77,NaN

In [60]:
df_census_reporter = pd.read_csv('census_reporter_demographic_df')

In [61]:
df_census_reporter

   zipcode  median age  per capita income  median household income
0    11215        37.0              87707                   156930
1    11217        35.5              85813                   133269
2    11218        36.4              43113                    81857
3    11225        36.1              41497                    68542
4    11226        35.4              34323                    66173
5    11238        35.3              67950                   114427

In [62]:
df_sun_exposure

,listing_path,location,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight data,No sunlight data available and the rent is 4033,5
1,m-g7pk2u6bgdl7,11216,21,0,680.0,2950,Limited natural light,This apartment has limited sunlight and the re...,2
2,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight data,No sunlight data available and the rent is 1918,None
3,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight data,No sunlight data available and the rent is 2035,2
4,m-5l5sbh0q5cdi,11216,1A,0,0.0,2696,No sunlight data,No sunlight data available and the rent is 2696,1
...,...,...,...,...,...,...,...,...,...
255,m-t8p0q78tlp5k,11221,A2,0,0.0,3449,Bright & sun drenched,Bright & sun drenched and the rent is 3449,2
256,m-a3poj9qc2mh8,11221,3F,1,9999.0,2250,Limited natural light,This apartment has limited sunlight and the re...,3
257,l-40dte2cunttt,11221,3R,1,NaN,2400,No sunlight data,No sunlight data available and the rent is 2400,3
258,l-sk18vv1pjmct,11221,2,1,NaN,2700,No sunlight data,No sunlight data available and the rent is 2700,2
259,m-9en3gqdfipkt,11221,6B,1,0.0,2292,No sunlight data,No sunlight data available and the rent is 2292,6

In [63]:
df_sun_exposure = df_sun_exposure.rename(columns = {'location':'zipcode'})

In [64]:
df_sun_exposure

,listing_path,zipcode,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight data,No sunlight data available and the rent is 4033,5
1,m-g7pk2u6bgdl7,11216,21,0,680.0,2950,Limited natural light,This apartment has limited sunlight and the re...,2
2,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight data,No sunlight data available and the rent is 1918,None
3,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight data,No sunlight data available and the rent is 2035,2
4,m-5l5sbh0q5cdi,11216,1A,0,0.0,2696,No sunlight data,No sunlight data available and the rent is 2696,1
...,...,...,...,...,...,...,...,...,...
255,m-t8p0q78tlp5k,11221,A2,0,0.0,3449,Bright & sun drenched,Bright & sun drenched and the rent is 3449,2
256,m-a3poj9qc2mh8,11221,3F,1,9999.0,2250,Limited natural light,This apartment has limited sunlight and the re...,3
257,l-40dte2cunttt,11221,3R,1,NaN,2400,No sunlight data,No sunlight data available and the rent is 2400,3
258,l-sk18vv1pjmct,11221,2,1,NaN,2700,No sunlight data,No sunlight data available and the rent is 2700,2
259,m-9en3gqdfipkt,11221,6B,1,0.0,2292,No sunlight data,No sunlight data available and the rent is 2292,6

In [65]:
df_sun_exposure_selected = df_sun_exposure[df_sun_exposure['zipcode'].isin(selected_zipcodes)]
df_sun_exposure_selected.reset_index(drop = True, inplace = True)
df_sun_exposure_selected

,listing_path,zipcode,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight data,No sunlight data available and the rent is 4033,5
1,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight data,No sunlight data available and the rent is 1918,None
2,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight data,No sunlight data available and the rent is 2035,2
3,m-fuijvl2a4kvv,11226,4E,1,500.0,2032,No sunlight data,No sunlight data available and the rent is 2032,4
4,m-9tfhakmgmkv0,11226,3A,1,593.0,2027,No sunlight data,No sunlight data available and the rent is 2027,3
...,...,...,...,...,...,...,...,...,...
98,l-5sr3mraftvdo,11238,1C,1,1196.0,5595,Limited natural light,This apartment has limited sunlight and the re...,1
99,l-9417psnrdkqb,11238,4B,1,665.0,3600,No sunlight data,No sunlight data available and the rent is 3600,4
100,m-oc27u40tqu3k,11238,5E,1,0.0,2350,Limited natural light,Limited natural light and the rent is 2350,5
101,m-6aoa0jitd5d7,11238,3C,1,9999.0,2600,No sunlight data,No sunlight data available and the rent is 2600,3
102,l-ue6jib37qqnf,11238,4,1,NaN,3500,No sunlight data,No sunlight data available and the rent is 3500,4

In [66]:
chart = alt.Chart(df_sun_exposure_selected)

In [67]:
alt.Chart(df_sun_exposure_selected).mark_bar().encode(
    x='zipcode',
    y='average(rent)'
)

alt.Chart(...)

In [68]:
chart = alt.Chart

In [69]:
subset = df_acs_selected_zipcodes[['zipcode', 'total', '18 to 34 years:']].copy()

In [70]:
subset['percentage'] = (subset['18 to 34 years:'] / subset['total']) * 100

In [71]:
chart = alt.Chart(subset).mark_bar().encode(
    x='zipcode:N',
    y='percentage:Q',
).properties(
    width=600,
    height=400
)

In [72]:
chart

alt.Chart(...)

In [73]:
df_acs_selected_zipcodes

,geoid,zipcode,total,lives alone,householder living with spouse or spouse of householder,householder living with unmarried partner or unmarried partner of householder,child of householder,other relatives,other nonrelatives,18 to 34 years:,...,child of householder.2,other relatives.2,other nonrelatives.2,65 years and over:,lives alone.3,householder living with spouse or spouse of householder.3,householder living with unmarried partner or unmarried partner of householder.3,child of householder.3,other relatives.3,other nonrelatives.3
0,86000US11215,11215,56580,7522,29844,5705,3361,4359,5789,16567,...,672,2357,1552,7889,1684,4468,243,11,1104,379
1,86000US11217,11217,33427,6388,12215,4630,2308,3794,4092,12560,...,454,2017,1163,4482,1361,1823,169,34,879,216
2,86000US11218,11218,54613,6965,25500,2770,7418,8187,3773,15461,...,1474,3742,1260,9352,2521,3738,200,30,2618,245
3,86000US11225,11225,48984,8978,12766,3832,6997,10241,6170,18374,...,1815,4358,1291,9414,3194,2605,156,45,3121,293
4,86000US11226,11226,78956,11590,20624,4652,13136,20512,8442,28997,...,3213,10028,2535,12353,3147,3543,250,42,4913,458
5,86000US11238,11238,47998,9299,16884,5428,3323,4747,8317,19005,...,1062,2441,1544,6352,2182,2120,272,7,1421,350

In [74]:
# living_arrangements_cols = ['lives alone.1', 'householder living with spouse or spouse of householder.1',
#                             'householder living with unmarried partner or unmarried partner of householder.1',
#                             'child of householder.1', 'other relatives.1', 'other nonrelatives.1']

In [75]:
# subset = df_acs_selected_zipcodes[['zipcode', '18 to 34 years:'] + living_arrangements_cols].copy()

In [76]:
# subset['total'] = subset[living_arrangements_cols].sum(axis=1)

# for col in living_arrangements_cols:
#     subset[col] = (subset[col] / subset['total']) * 100

In [77]:
# melted = subset.melt(id_vars=['zipcode', '18 to 34 years:', 'total'], value_vars=living_arrangements_cols)

In [78]:
# chart = alt.Chart(melted).mark_bar().encode(
#     x=alt.X('zipcode:N', axis=alt.Axis(title='Zip Code')),
#     y=alt.Y('value:Q', axis=alt.Axis(title='Percentage')),
#     color=alt.Color('variable:N', legend=alt.Legend(title='Living Arrangement')),
#     column=alt.Column('18 to 34 years', title='Age Group'),
#     tooltip=['zipcode', 'variable', 'value']
# ).properties(
#     width=150,
#     height=400
# )

# chart

In [79]:
# chart = alt.Chart(melted).mark_bar().encode(
#     x=alt.X('zipcode:N', axis=alt.Axis(title='Zip Code')),
#     y=alt.Y('value:Q', axis=alt.Axis(title='Percentage')),
#     color=alt.Color('variable:N', legend=alt.Legend(title='Living Arrangement')),
#     tooltip=['zipcode', 'variable', 'value']
# ).properties(
#     width=800,
#     height=400
# ).facet(
#     row=alt.Row('variable:N', title='Living Arrangement', header=alt.Header(labelAngle=-90)),
#     data=melted
# )

# # Display the chart
# chart

In [80]:
df_acs_selected_zipcodes = df_acs_selected_zipcodes.copy()
df_acs_selected_zipcodes.loc[:, 'total'] = pd.to_numeric(df_acs_selected_zipcodes['total'], errors='coerce')

# Calculate the percentage of each living arrangement category
living_arrangements_cols = ['lives alone.1', 'householder living with spouse or spouse of householder.1',
                            'householder living with unmarried partner or unmarried partner of householder.1',
                            'child of householder.1', 'other relatives.1', 'other nonrelatives.1']
df_acs_selected_zipcodes_percent = df_acs_selected_zipcodes.copy()
df_acs_selected_zipcodes_percent.loc[:, living_arrangements_cols] = (
    df_acs_selected_zipcodes_percent[living_arrangements_cols].div(df_acs_selected_zipcodes_percent['18 to 34 years:'], axis=0) * 100
).astype(int)

In [81]:
melted = pd.melt(df_acs_selected_zipcodes_percent, id_vars='zipcode', value_vars=living_arrangements_cols, var_name='living_arrangement', value_name='percentage')

# Create the stacked bar chart
chart = alt.Chart(melted).mark_bar().encode(
    x=alt.X('zipcode:N', axis=alt.Axis(title='Zip Code')),
    y=alt.Y('percentage:Q', axis=alt.Axis(title='Percentage')),
    color=alt.Color('living_arrangement:N', legend=alt.Legend(title='Living Arrangement')),
    tooltip=['zipcode', 'living_arrangement', 'percentage']
).properties(
    width=800,
    height=400
)

# Display the chart
chart

alt.Chart(...)

In [82]:
f"The median age for this area is {df_census_reporter['median age'].median().astype(int)}."

'The median age for this area is 35.'

In [83]:
y_scale = alt.Scale(domain=[30, 40]) #cuts the axis

In [84]:
scatter_plot = alt.Chart(df_census_reporter).mark_circle().encode(
    x='zipcode:O',
    y=alt.Y('median age:Q', scale=y_scale),
    size='per capita income:Q',
    color='median household income:Q',
    tooltip=['zipcode:N', 'median age:Q', 'per capita income:Q', 'median household income:Q']
).properties(
    width=600,
    height=400
)
scatter_plot

alt.Chart(...)

In [85]:
df_sun_exposure_selected

,listing_path,zipcode,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
0,l-l4njo7ppbf0p,11238,509,1,NaN,4033,No sunlight data,No sunlight data available and the rent is 4033,5
1,m-k641hj441qsf,11226,b,1,1000.0,1918,No sunlight data,No sunlight data available and the rent is 1918,None
2,m-7m7ugsdf31rv,11226,2B,1,675.0,2035,No sunlight data,No sunlight data available and the rent is 2035,2
3,m-fuijvl2a4kvv,11226,4E,1,500.0,2032,No sunlight data,No sunlight data available and the rent is 2032,4
4,m-9tfhakmgmkv0,11226,3A,1,593.0,2027,No sunlight data,No sunlight data available and the rent is 2027,3
...,...,...,...,...,...,...,...,...,...
98,l-5sr3mraftvdo,11238,1C,1,1196.0,5595,Limited natural light,This apartment has limited sunlight and the re...,1
99,l-9417psnrdkqb,11238,4B,1,665.0,3600,No sunlight data,No sunlight data available and the rent is 3600,4
100,m-oc27u40tqu3k,11238,5E,1,0.0,2350,Limited natural light,Limited natural light and the rent is 2350,5
101,m-6aoa0jitd5d7,11238,3C,1,9999.0,2600,No sunlight data,No sunlight data available and the rent is 2600,3
102,l-ue6jib37qqnf,11238,4,1,NaN,3500,No sunlight data,No sunlight data available and the rent is 3500,4

In [86]:
bar_chart = alt.Chart(df_sun_exposure_selected).mark_bar().encode(
    x='sun_exposure_cat:N',
    y='count():Q',
    color='sun_exposure_cat:N',
    column='zipcode:N',
    tooltip=['zipcode:N', 'sun_exposure_cat:N', 'rent:Q']
).properties(
    width=200,
    height=300
)
bar_chart

alt.Chart(...)

In [87]:
bar_chart = alt.Chart(df_sun_exposure_selected).mark_bar().encode(
    x='sun_exposure_cat:N',
    y='mean(rent):Q',
    color='sun_exposure_cat:N',
    column='zipcode:N',
    tooltip=['zipcode:N', 'sun_exposure_cat:N', 'rent:Q']
).properties(
#     tooltip=['sun_exposure_cat:N', 'mean(rent):Q']
# ).properties(
    width=600,
    height=400
)

# Show the bar chart
bar_chart

alt.Chart(...)

In [88]:
chart = alt.Chart(df_sun_exposure).mark_bar().encode(
    x=alt.X('floor:O', title='Floor'),
    y=alt.Y('count()', title='Count'),
    color=alt.Color('sun_exposure_cat:N', title='Sun Exposure Category'),
    column=alt.Column('sun_exposure_cat:N', title='Sun Exposure Category'),
).properties(
    width=150,
    height=200
)

chart

alt.Chart(...)

In [89]:
filtered_sun_exposure = df_sun_exposure[df_sun_exposure['sun_exposure_cat'] != 'No sunlight data']

# Calculate the mode of the sun exposure category
common_sun_exposure = filtered_sun_exposure['sun_exposure_cat'].mode()[0]

print("The most common sun exposure category for apartment floors is:", common_sun_exposure)

The most common sun exposure category for apartment floors is: Limited natural light

In [90]:
common_sun_exposure_by_floor = filtered_sun_exposure.groupby('floor')['sun_exposure_cat'].apply(lambda x: x.mode()[0])

print("Most common sun exposure categories by floor:")
print(common_sun_exposure_by_floor)

Most common sun exposure categories by floor:
floor
1    Limited natural light
2    Limited natural light
3    Limited natural light
4    Limited natural light
5    Limited natural light
7    Limited natural light
9    Limited natural light
Name: sun_exposure_cat, dtype: object

In [91]:
filtered_sun_exposure[filtered_sun_exposure.sun_exposure_cat == 'Moderate sunlight']

,listing_path,zipcode,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
26,m-2errkn8o62in,11216,1FF,1,0.0,2049,Moderate sunlight,Moderate natural light and the rent is 2049,1
32,m-as4rgiinomc0,11216,2F,1,0.0,2095,Moderate sunlight,Moderate natural light and the rent is 2095,2
33,m-pjck846pllqe,11216,1B,0,0.0,1650,Moderate sunlight,Moderate natural light and the rent is 1650,1
34,m-alvdc30ctcdj,11226,3F3F,1,0.0,2000,Moderate sunlight,Moderate natural light and the rent is 2000,3
38,m-6uduhgo2kok0,11226,33FF,1,0.0,2099,Moderate sunlight,Moderate natural light and the rent is 2099,3
47,m-vtmqugvur0oh,11226,3F,1,0.0,2250,Moderate sunlight,Moderate natural light and the rent is 2250,3
49,m-3av8il4tckpa,11216,4B,1,0.0,2500,Moderate sunlight,Moderate natural light and the rent is 2500,4
52,m-da52rtlgbm82,11216,3B,1,0.0,2199,Moderate sunlight,Moderate natural light and the rent is 2199,3
103,l-j7tp78f9d067,11205,1,1,1471.0,5750,Moderate sunlight,This apartment has moderate sunlight and the r...,1
137,l-skpvkqbbue9j,11205,1L,1,NaN,4000,Moderate sunlight,This apartment has moderate sunlight and the r...,1
162,l-af04hjn8ih6a,11238,401,1,NaN,4500,Moderate sunlight,This apartment has moderate sunlight and the r...,4
174,m-ha3scum2sgo1,11216,4C,1,0.0,3300,Moderate sunlight,Moderate natural light and the rent is 3300,4
200,m-ngt4ph8udkmq,11216,4F,1,0.0,2125,Moderate sunlight,Moderate natural light and the rent is 2125,4
205,m-84sipv8lrh8v,11216,509,0,300.0,1650,Moderate sunlight,Moderate natural light and the rent is 1650,5
214,m-19loqn2udrop,11216,2,1,0.0,2825,Moderate sunlight,Moderate natural light and the rent is 2825,2
246,l-pj7cvotqbson,11221,3,1,NaN,3000,Moderate sunlight,This apartment has moderate sunlight and the r...,3
250,m-105edfbi2h3k,11221,2B,0,0.0,2150,Moderate sunlight,Moderate natural light and the rent is 2150,2
253,m-re8s2nn1ebt,11233,Unit 2D,1,750.0,1900,Moderate sunlight,Moderate natural light and the rent is 1900,2

In [92]:
chart = alt.Chart(filtered_sun_exposure).mark_boxplot().encode(
    x='sun_exposure_cat:N',
    y='rent:Q',
    color='sun_exposure_cat:N'
).properties(
    width=400,
    height=300
)

chart

alt.Chart(...)

In [93]:
filtered_sun_exposure.groupby('sun_exposure_cat')['rent'].describe()

,count,mean,std,min,25%,50%,75%,max
sun_exposure_cat,,,,,,,,
Bright & sun drenched,2.0,2749.500000,989.242387,2050.0,2399.75,2749.5,3099.25,3449.0
Limited natural light,48.0,2585.333333,656.722952,1700.0,2100.00,2400.0,2896.00,5595.0
Moderate sunlight,18.0,2669.000000,1092.581401,1650.0,2060.50,2174.5,2956.25,5750.0

In [94]:
df_sun_exposure.groupby('sun_exposure_cat')['rent'].describe()

,count,mean,std,min,25%,50%,75%,max
sun_exposure_cat,,,,,,,,
Bright & sun drenched,2.0,2749.500000,989.242387,2050.0,2399.75,2749.5,3099.25,3449.0
Limited natural light,48.0,2585.333333,656.722952,1700.0,2100.00,2400.0,2896.00,5595.0
Moderate sunlight,18.0,2669.000000,1092.581401,1650.0,2060.50,2174.5,2956.25,5750.0
No sunlight data,192.0,2734.338542,679.114079,900.0,2200.00,2600.0,3053.50,5585.0

In [95]:
df_sun_exposure.groupby('floor')['rent'].mean().astype(int)

floor
1    2926
2    2522
3    2643
4    2736
5    2750
6    2409
7    3016
8    3021
9    2586
Name: rent, dtype: int64

In [96]:
filtered_sun_exposure\
    .sort_values(by='sun_exposure_cat', ascending = False)\
    .sort_values(by = 'rent', ascending = False)\
    .sort_values(by = 'floor', ascending = False)

,listing_path,zipcode,unit_number,beds,size,rent,sun_exposure_cat,sun_exposure,floor
190,m-qedem2h2qs8t,11216,9,1,9999.0,1700,Limited natural light,Limited natural light and the rent is 1700,9
27,m-7vhvbui4fp5j,11216,7,1,0.0,2025,Limited natural light,Limited natural light and the rent is 2025,7
209,m-jag808dc459v,11206,7A,1,0.0,2149,Limited natural light,Limited natural light and the rent is 2149,7
127,l-qh300dtif0ah,11205,5D,1,NaN,3545,Limited natural light,This apartment has limited sunlight and the re...,5
169,m-oc27u40tqu3k,11238,5E,1,0.0,2350,Limited natural light,Limited natural light and the rent is 2350,5
...,...,...,...,...,...,...,...,...,...
92,l-4glljujjq02r,11213,1,1,1000.0,3000,Limited natural light,This apartment has limited sunlight and the re...,1
95,l-qj7plb01m2m0,11216,1,1,NaN,3200,Limited natural light,This apartment has limited sunlight and the re...,1
207,l-qp91auide8ca,11206,1,1,NaN,3200,Limited natural light,This apartment has limited sunlight and the re...,1
137,l-skpvkqbbue9j,11205,1L,1,NaN,4000,Moderate sunlight,This apartment has moderate sunlight and the r...,1
33,m-pjck846pllqe,11216,1B,0,0.0,1650,Moderate sunlight,Moderate natural light and the rent is 1650,1

In [97]:
rent_by_zipcode = filtered_sun_exposure.groupby(['zipcode', 'sun_exposure_cat','floor'])['rent'].median().reset_index()

# Create a scatter plot to visualize the rent distribution by sun exposure category and zipcode
chart = alt.Chart(rent_by_zipcode).mark_circle().encode(
    x='zipcode:N',
    y='rent:Q',
    color='sun_exposure_cat:N',
    tooltip=['zipcode:N', 'sun_exposure_cat:N', 'rent:Q', 'floor:N']
).properties(
    width=600,
    height=400
)

chart

alt.Chart(...)

In [98]:
sun_floor = filtered_sun_exposure[['floor', 'sun_exposure_cat','rent','zipcode']]\
    .copy()\
    .sort_values('floor', ascending = False)\
    .reset_index(drop=True)
sun_floor
# sun_floor.to_csv('sun_and_floor.csv', index = False)

   floor       sun_exposure_cat  rent zipcode
0      9  Limited natural light  1700   11216
1      7  Limited natural light  2025   11216
2      7  Limited natural light  2149   11206
3      5  Limited natural light  3545   11205
4      5  Limited natural light  2050   11216
..   ...                    ...   ...     ...
63     1  Limited natural light  2400   11216
64     1  Limited natural light  1950   11205
65     1      Moderate sunlight  1650   11216
66     1  Limited natural light  2000   11206
67     1  Limited natural light  3200   11216

[68 rows x 4 columns]